### ISSUE TITLE
Is the resolution of version ranges supported?

### ISSUE THREAD

**Issue by Elijas** [astariul/github-hosted-pypi#67]
I have a requirements.txt file with the following contents:
```
my_custom_package>=1.0.0,<2.0.0
my_other_package>=1.18.0,<1.20.0
```
Will the version ranges be resolved, or is it necessary to use a PyPI server to handle the version resolution?

**Comment by astariul** [comment]
Hey, thank for the excellent question. And sorry about the late reply..

---

Yes ! Version ranges are resolved by `pip`, when you run the command. 

So you can use this repository even if you requirements are ranged-based. `github-hosted-pypi` is basically just a list of versions with links, `pip` retrieves this list, resolve the version to install, then follow the link to install the package.
