### ISSUE TITLE
Update styles and actions 

### ISSUE THREAD

**Issue by santiagoUnlitrobotics** [astariul/github-hosted-pypi#70]

**Comment by santiagoUnlitrobotics** [comment]
I have some changes that improves the workflows and add some changes on the css, i need permissions to push this changes and create the PR

**Comment by astariul** [comment]
@santiagoUnlitrobotics Yeah sure !

Please fork the repository, push your changes in a branch, and open a PR in this repository, I'll be glad to review it !

**Comment by pabnas** [comment]
@astariul This is my main account, i already create the PR.
https://github.com/astariul/github-hosted-pypi/pull/71
